-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.19 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table vb5_manual.documentation_page
DROP TABLE IF EXISTS `documentation_page`;
CREATE TABLE IF NOT EXISTS `documentation_page` (
  `guid` varchar(250) NOT NULL,
  `title` varchar(250) NOT NULL,
  `documentation` text,
  `modules` text,
  `imagepath` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

-- Dumping data for table vb5_manual.documentation_page: 48 rows
DELETE FROM `documentation_page`;
/*!40000 ALTER TABLE `documentation_page` DISABLE KEYS */;
INSERT INTO `documentation_page` (`guid`, `title`, `documentation`, `modules`, `imagepath`) VALUES
	('vbulletin-page-resetpassword-5697fafcd94565.15617388', 'Reset Password', NULL, NULL, NULL),
	('vbulletin-page-apiform-5605aecbbf06b9.20659158', 'vBulletin API Form', NULL, NULL, NULL),
	('vbulletin-page-markuplibrary-982343cdd2300198e.2309864921', 'vBulletin Markup Library', NULL, NULL, NULL),
	('vbulletin-p-cmsarticle522a1de52295d8.35615179', 'Article', NULL, NULL, NULL),
	('vbulletin-p-cmshome5229f4e0c2ea71.91676461', 'Articles', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f07a5.18983926', 'Member List', NULL, NULL, NULL),
	('vbulletin-513e3ae1ecdf97.38916583', 'CSS Examples Page', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323376', 'Coppa Permission Form', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323375', 'Email Activation Codes', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323374', 'Activate Your Account', NULL, NULL, NULL),
	('vbulletin-vbsgcatlistf2c27.60323373', 'Group Category', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323372', 'Group Home', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323370', 'Group Admin', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323369', 'Create New Content', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323367', 'Blog Admin', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323366', 'Blogs', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323365', 'Visitor Message Display', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323364', 'Album', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323362', 'Subscription', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2c27.60323361', 'Message Center', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2815.04471586', 'Search Result', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f2408.19539885', 'User Settings', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f13d1.77590572', 'Edit Photos', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f0fd1.78471901', 'Media', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f0bb4.37025811', 'User Profile', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f07a5.18983925', 'Who\'s Online', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f0396.95291108', 'Help', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f0396.95291107', 'Contact Us', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f0396.95291106', 'Forgot Password', NULL, NULL, NULL),
	('vbulletin-4ecbdac82f0396.95291105', 'Register', NULL, NULL, NULL),
	('vbulletin-4ecbdac82efb61.17736147', 'Advanced Search', NULL, NULL, NULL),
	('vbulletin-4ecbdac82ef5d4.12817784', 'Forums', NULL, NULL, NULL),
	('vbulletin-pmchat-page-chat-573cba8f1d2283.90944371', 'vB Messenger Page', NULL, NULL, NULL),
	('vbulletin-page-calendar-58af7bf507c036.07102564', 'Calendar', NULL, NULL, NULL),
	('vbulletin-5a304600162e58.89585634', 'Forum', NULL, NULL, NULL),
	('vbulletin-5a304601c27884.90109607', 'Main Forum', NULL, NULL, NULL),
	('vbulletin-5a304602c9b0e7.85846735', 'Main Forum', NULL, NULL, NULL),
	('vbulletin-5a304603a214f0.42722842', 'Special', NULL, NULL, NULL),
	('vbulletin-5a304604d072f2.52418389', 'Visitor Messages', NULL, NULL, NULL),
	('vbulletin-5a3046060e6718.75680979', 'Visitor Messages', NULL, NULL, NULL),
	('vbulletin-5a304607857047.79985701', 'Private Messages', NULL, NULL, NULL),
	('vbulletin-5a3046084b94e6.23042844', 'Private Messages', NULL, NULL, NULL),
	('vbulletin-5a304609b81c68.66972117', 'Albums', NULL, NULL, NULL),
	('vbulletin-5a30460be23d81.35569779', 'Albums', NULL, NULL, NULL),
	('vbulletin-5a30460e8a1b63.32161627', 'Reports', NULL, NULL, NULL),
	('vbulletin-5a30460fe4e703.61381916', 'Reports', NULL, NULL, NULL),
	('vbulletin-5a30461081a002.72995571', 'Infractions', NULL, NULL, NULL),
	('vbulletin-5a304610ede267.58387024', 'Infractions', NULL, NULL, NULL);
/*!40000 ALTER TABLE `documentation_page` ENABLE KEYS */;

-- Dumping structure for table vb5_manual.documentation_setting
DROP TABLE IF EXISTS `documentation_setting`;
CREATE TABLE IF NOT EXISTS `documentation_setting` (
  `varname` varchar(250) NOT NULL,
  `documentation` text NOT NULL,
  `example` text NOT NULL,
  `imagepath` varchar(250) NOT NULL,
  PRIMARY KEY (`varname`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

-- Dumping data for table vb5_manual.documentation_setting: 0 rows
DELETE FROM `documentation_setting`;
/*!40000 ALTER TABLE `documentation_setting` DISABLE KEYS */;
/*!40000 ALTER TABLE `documentation_setting` ENABLE KEYS */;

-- Dumping structure for table vb5_manual.documentation_settinggroup
DROP TABLE IF EXISTS `documentation_settinggroup`;
CREATE TABLE IF NOT EXISTS `documentation_settinggroup` (
  `grouptitle` varchar(50) NOT NULL,
  `documentation` text NOT NULL,
  `imagepath` varchar(250) NOT NULL,
  PRIMARY KEY (`grouptitle`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

-- Dumping data for table vb5_manual.documentation_settinggroup: 0 rows
DELETE FROM `documentation_settinggroup`;
/*!40000 ALTER TABLE `documentation_settinggroup` DISABLE KEYS */;
/*!40000 ALTER TABLE `documentation_settinggroup` ENABLE KEYS */;

-- Dumping structure for table vb5_manual.documentation_stylevar
DROP TABLE IF EXISTS `documentation_stylevar`;
CREATE TABLE IF NOT EXISTS `documentation_stylevar` (
  `stylevarid` varchar(250) DEFAULT NULL,
  `documentation` text,
  `examples` text
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

-- Dumping data for table vb5_manual.documentation_stylevar: 384 rows
DELETE FROM `documentation_stylevar`;
/*!40000 ALTER TABLE `documentation_stylevar` DISABLE KEYS */;
INSERT INTO `documentation_stylevar` (`stylevarid`, `documentation`, `examples`) VALUES
	('activity_stream_avatar_border', NULL, NULL),
	('activity_stream_content_padding', NULL, NULL),
	('announcement_background', NULL, NULL),
	('announcement_border', NULL, NULL),
	('announcement_text_color', NULL, NULL),
	('autosuggest_background', NULL, NULL),
	('autosuggest_background_active', NULL, NULL),
	('bbcode_code_background', NULL, NULL),
	('bbcode_code_border', NULL, NULL),
	('bbcode_code_fontsize', NULL, NULL),
	('bbcode_code_line_height', NULL, NULL),
	('bbcode_quote_background', NULL, NULL),
	('body_background', NULL, NULL),
	('body_font', NULL, NULL),
	('body_line_height', NULL, NULL),
	('body_link_color', NULL, NULL),
	('body_link_color_hover', NULL, NULL),
	('body_link_decoration', NULL, NULL),
	('body_link_decoration_hover', NULL, NULL),
	('body_text_color', NULL, NULL),
	('breadcrumb_background', NULL, NULL),
	('breadcrumb_font', NULL, NULL),
	('breadcrumb_link_color', NULL, NULL),
	('breadcrumb_text_color', NULL, NULL),
	('breadcrumb_text_transform', NULL, NULL),
	('button_arrow_background', NULL, NULL),
	('button_arrow_border', NULL, NULL),
	('button_disabled_background', NULL, NULL),
	('button_disabled_border', NULL, NULL),
	('button_disabled_text_color', NULL, NULL),
	('button_font', NULL, NULL),
	('button_primary_background', NULL, NULL),
	('button_primary_background_hover', NULL, NULL),
	('button_primary_border', NULL, NULL),
	('button_primary_border_hover', NULL, NULL),
	('button_primary_light_background', NULL, NULL),
	('button_primary_light_border', NULL, NULL),
	('button_primary_light_border_hover', NULL, NULL),
	('button_primary_light_text_color', NULL, NULL),
	('button_primary_text_color', NULL, NULL),
	('button_primary_text_color_hover', NULL, NULL),
	('button_secondary_background', NULL, NULL),
	('button_secondary_border', NULL, NULL),
	('button_secondary_border_hover', NULL, NULL),
	('button_secondary_text_color', NULL, NULL),
	('button_special_background', NULL, NULL),
	('button_special_border', NULL, NULL),
	('button_special_border_hover', NULL, NULL),
	('button_special_text_color', NULL, NULL),
	('calendar_event_background', NULL, NULL),
	('calendar_event_background_hover', NULL, NULL),
	('calendar_event_border', NULL, NULL),
	('calendar_event_text_color', NULL, NULL),
	('calendar_event_text_color_hover', NULL, NULL),
	('calendar_event_text_decoration', NULL, NULL),
	('calendar_event_text_decoration_hover', NULL, NULL),
	('calendar_more_link_color', NULL, NULL),
	('calendar_more_link_color_hover', NULL, NULL),
	('calendar_more_link_decoration', NULL, NULL),
	('calendar_more_link_decoration_hover', NULL, NULL),
	('comment_background', NULL, NULL),
	('comment_divider_color', NULL, NULL),
	('contententry_autosave_background', NULL, NULL),
	('contententry_autosave_text_color', NULL, NULL),
	('contententry_panel_background', NULL, NULL),
	('contententry_panel_section_background', NULL, NULL),
	('contententry_panel_section_title_background', NULL, NULL),
	('contententry_toolbar_background', NULL, NULL),
	('contententry_toolbar_button_secondary_background', NULL, NULL),
	('contententry_toolbar_button_secondary_background_active', NULL, NULL),
	('contententry_toolbar_button_secondary_border', NULL, NULL),
	('content_background', NULL, NULL),
	('content_divider_color', NULL, NULL),
	('content_entry_box_header_text_color', NULL, NULL),
	('diff_add_background', NULL, NULL),
	('diff_add_color', NULL, NULL),
	('diff_remove_background', NULL, NULL),
	('diff_remove_color', NULL, NULL),
	('favicon', NULL, NULL),
	('footer_background', NULL, NULL),
	('footer_border', NULL, NULL),
	('footer_copyright_text_color', NULL, NULL),
	('footer_font_style', NULL, NULL),
	('footer_height', NULL, NULL),
	('footer_list_item_color', NULL, NULL),
	('footer_list_item_color_hover', NULL, NULL),
	('footer_list_item_divider_color', NULL, NULL),
	('footer_list_item_spacing', NULL, NULL),
	('footer_list_item_text_decoration', NULL, NULL),
	('footer_list_item_text_decoration_hover', NULL, NULL),
	('footer_text_transform', NULL, NULL),
	('form_background', NULL, NULL),
	('form_border', NULL, NULL),
	('form_dropdown_background', NULL, NULL),
	('form_dropdown_background_hover', NULL, NULL),
	('form_dropdown_border', NULL, NULL),
	('form_dropdown_text_color', NULL, NULL),
	('form_dropdown_text_color_hover', NULL, NULL),
	('form_field_background', NULL, NULL),
	('form_field_border', NULL, NULL),
	('form_field_text_color', NULL, NULL),
	('forum_list_category_font', NULL, NULL),
	('forum_list_header_font', NULL, NULL),
	('header_background', NULL, NULL),
	('header_height', NULL, NULL),
	('header_search_button_background', NULL, NULL),
	('header_search_button_border', NULL, NULL),
	('header_search_button_text_color', NULL, NULL),
	('header_search_input_background', NULL, NULL),
	('header_search_input_border', NULL, NULL),
	('header_search_input_text_color', NULL, NULL),
	('header_search_placeholder_text_color', NULL, NULL),
	('header_subtabbar_background', NULL, NULL),
	('header_subtabbar_border', NULL, NULL),
	('header_subtabbar_font', NULL, NULL),
	('header_subtabbar_height', NULL, NULL),
	('header_subtabbar_link_margin', NULL, NULL),
	('header_subtabbar_text_color', NULL, NULL),
	('header_subtabbar_text_color_hover', NULL, NULL),
	('header_subtabbar_text_decoration', NULL, NULL),
	('header_subtabbar_text_decoration_hover', NULL, NULL),
	('header_subtabbar_text_transform', NULL, NULL),
	('header_tabbar_background', NULL, NULL),
	('header_tabbar_border', NULL, NULL),
	('header_tabbar_divider_border', NULL, NULL),
	('header_tabbar_height', NULL, NULL),
	('header_tabbar_top_border', NULL, NULL),
	('header_tab_background', NULL, NULL),
	('header_tab_background_active', NULL, NULL),
	('header_tab_background_hover', NULL, NULL),
	('header_tab_border_active', NULL, NULL),
	('header_tab_border_radius_size', NULL, NULL),
	('header_tab_bottom_border_active', NULL, NULL),
	('header_tab_bottom_border_radius_size', NULL, NULL),
	('header_tab_font', NULL, NULL),
	('header_tab_font_active', NULL, NULL),
	('header_tab_height', NULL, NULL),
	('header_tab_line_height', NULL, NULL),
	('header_tab_margin', NULL, NULL),
	('header_tab_padding', NULL, NULL),
	('header_tab_text_color', NULL, NULL),
	('header_tab_text_color_active', NULL, NULL),
	('header_tab_text_color_hover', NULL, NULL),
	('header_tab_text_decoration', NULL, NULL),
	('header_tab_text_decoration_active', NULL, NULL),
	('header_tab_text_decoration_hover', NULL, NULL),
	('header_tab_text_transform', NULL, NULL),
	('header_text_color', NULL, NULL),
	('imgdir_attach', NULL, NULL),
	('imgdir_button', NULL, NULL),
	('imgdir_misc', NULL, NULL),
	('imgdir_spriteiconsvb', NULL, NULL),
	('imgdir_statusicon', NULL, NULL),
	('inline_edit_background', NULL, NULL),
	('inline_edit_button_border', NULL, NULL),
	('inline_edit_button_disabled_text_color', NULL, NULL),
	('inline_edit_button_divider_left_color', NULL, NULL),
	('inline_edit_button_divider_right_color', NULL, NULL),
	('inline_edit_button_flat_text_color', NULL, NULL),
	('inline_edit_button_primary_text_color', NULL, NULL),
	('inline_edit_button_secondary_text_color', NULL, NULL),
	('inline_edit_field_border', NULL, NULL),
	('inline_edit_folder_active_color', NULL, NULL),
	('inline_edit_folder_inner_highlight_color', NULL, NULL),
	('inline_edit_folder_text_color_active_hover', NULL, NULL),
	('inline_edit_form_text_color', NULL, NULL),
	('inline_edit_header_body_text_color', NULL, NULL),
	('inline_edit_header_line_bottom_color', NULL, NULL),
	('inline_edit_header_line_top_color', NULL, NULL),
	('inline_edit_module_title_text_color', NULL, NULL),
	('inline_edit_popup_comment_line_color', NULL, NULL),
	('inline_edit_search_bar_background', NULL, NULL),
	('inline_edit_search_bar_background_active', NULL, NULL),
	('inline_edit_search_bar_background_hover', NULL, NULL),
	('inline_edit_search_bar_text_color', NULL, NULL),
	('inline_edit_search_text_active_color', NULL, NULL),
	('inline_edit_subheader_text_color', NULL, NULL),
	('list_item_background', NULL, NULL),
	('main_nav_admin_bar_background', NULL, NULL),
	('main_nav_admin_bar_bottom_line_background', NULL, NULL),
	('main_nav_admin_bar_bottom_line_height', NULL, NULL),
	('main_nav_admin_bar_divider_left_color', NULL, NULL),
	('main_nav_admin_bar_divider_right_color', NULL, NULL),
	('main_nav_admin_bar_text_color', NULL, NULL),
	('main_nav_admin_bar_text_color_hover', NULL, NULL),
	('main_nav_admin_bar_text_disabled_color', NULL, NULL),
	('main_nav_button_border', NULL, NULL),
	('main_nav_login_error_field_background', NULL, NULL),
	('main_nav_login_error_text_color', NULL, NULL),
	('module_contentslider_background', NULL, NULL),
	('module_contentslider_border', NULL, NULL),
	('module_contentslider_caption_background', NULL, NULL),
	('module_contentslider_caption_text_color', NULL, NULL),
	('module_contentslider_height', NULL, NULL),
	('module_content_background', NULL, NULL),
	('module_content_border', NULL, NULL),
	('module_header_background', NULL, NULL),
	('module_header_border', NULL, NULL),
	('module_header_divider_margin', NULL, NULL),
	('module_header_font', NULL, NULL),
	('module_header_text_align', NULL, NULL),
	('module_header_text_color', NULL, NULL),
	('module_header_text_transform', NULL, NULL),
	('module_search_list_item_border', NULL, NULL),
	('module_tabbar_border_radius_size', NULL, NULL),
	('module_tab_background', NULL, NULL),
	('module_tab_background_active', NULL, NULL),
	('module_tab_border', NULL, NULL),
	('module_tab_border_active', NULL, NULL),
	('module_tab_border_radius_size', NULL, NULL),
	('module_tab_font', NULL, NULL),
	('module_tab_height', NULL, NULL),
	('module_tab_text_color', NULL, NULL),
	('module_tab_text_color_active', NULL, NULL),
	('module_tab_text_color_hover', NULL, NULL),
	('module_tab_text_decoration', NULL, NULL),
	('module_tab_text_decoration_active', NULL, NULL),
	('module_tab_text_decoration_hover', NULL, NULL),
	('module_tab_text_transform', NULL, NULL),
	('notice_background', NULL, NULL),
	('notice_border', NULL, NULL),
	('notice_text_color', NULL, NULL),
	('notification_detail_unread_background', NULL, NULL),
	('no_content_background', NULL, NULL),
	('pagination_nextprev_divider_left_color', NULL, NULL),
	('pagination_nextprev_divider_right_color', NULL, NULL),
	('photo_background', NULL, NULL),
	('photo_border', NULL, NULL),
	('photo_border_hover', NULL, NULL),
	('photo_preview_background', NULL, NULL),
	('photo_preview_border', NULL, NULL),
	('placeholder_text_color', NULL, NULL),
	('poll_result_border', NULL, NULL),
	('poll_result_color_01', NULL, NULL),
	('poll_result_color_02', NULL, NULL),
	('poll_result_color_03', NULL, NULL),
	('poll_result_color_04', NULL, NULL),
	('poll_result_color_05', NULL, NULL),
	('poll_result_color_06', NULL, NULL),
	('poll_result_color_07', NULL, NULL),
	('poll_result_color_08', NULL, NULL),
	('poll_result_color_09', NULL, NULL),
	('poll_result_color_10', NULL, NULL),
	('poll_result_color_11', NULL, NULL),
	('poll_result_color_12', NULL, NULL),
	('poll_result_percentage_background', NULL, NULL),
	('poll_result_vote_count_text', NULL, NULL),
	('popup_background', NULL, NULL),
	('popup_border', NULL, NULL),
	('popup_header_background', NULL, NULL),
	('popup_header_text_color', NULL, NULL),
	('popup_overlay_background', NULL, NULL),
	('postbit_background', NULL, NULL),
	('postbit_deleted_background', NULL, NULL),
	('postbit_unapproved_background', NULL, NULL),
	('post_border', NULL, NULL),
	('post_content_font', NULL, NULL),
	('post_controls_divider_color', NULL, NULL),
	('post_controls_quote_active_text_color', NULL, NULL),
	('post_controls_text_color', NULL, NULL),
	('post_controls_votes_border', NULL, NULL),
	('post_deleted_border', NULL, NULL),
	('post_rating_color', NULL, NULL),
	('post_username_color', NULL, NULL),
	('post_user_info_color', NULL, NULL),
	('primary_module_background', NULL, NULL),
	('primary_module_border', NULL, NULL),
	('primary_module_header_background', NULL, NULL),
	('primary_module_header_font', NULL, NULL),
	('primary_module_header_text_align', NULL, NULL),
	('primary_module_header_text_color', NULL, NULL),
	('primary_module_header_text_transform', NULL, NULL),
	('primary_module_subheader_background', NULL, NULL),
	('primary_module_subheader_border', NULL, NULL),
	('primary_module_subheader_font', NULL, NULL),
	('primary_module_subheader_text_color', NULL, NULL),
	('private_messages_mark_as_unread_background', NULL, NULL),
	('profcustom_navbarbuttonsecondary_background', NULL, NULL),
	('profcustom_navbarbuttonsecondary_border', NULL, NULL),
	('profcustom_navbarbuttonsecondary_color', NULL, NULL),
	('profcustom_navbarbutton_background', NULL, NULL),
	('profcustom_navbarbutton_border', NULL, NULL),
	('profcustom_navbarbutton_color', NULL, NULL),
	('profcustom_navbar_background', NULL, NULL),
	('profcustom_navbar_background_active', NULL, NULL),
	('profcustom_navbar_border', NULL, NULL),
	('profcustom_navbar_border_active', NULL, NULL),
	('profcustom_navbar_text_color', NULL, NULL),
	('profcustom_navbar_text_color_active', NULL, NULL),
	('profcustom_navbar_toolbar_text_color', NULL, NULL),
	('profilesidebar_button_background', NULL, NULL),
	('profilesidebar_button_border', NULL, NULL),
	('profilesidebar_button_text_color', NULL, NULL),
	('profilesidebar_count_text_color', NULL, NULL),
	('profile_button_primary_background', NULL, NULL),
	('profile_button_secondary_background', NULL, NULL),
	('profile_content_background', NULL, NULL),
	('profile_content_border', NULL, NULL),
	('profile_content_divider_border', NULL, NULL),
	('profile_content_font', NULL, NULL),
	('profile_content_linktext', NULL, NULL),
	('profile_content_primarytext', NULL, NULL),
	('profile_content_secondarytext', NULL, NULL),
	('profile_section_background', NULL, NULL),
	('profile_section_border', NULL, NULL),
	('profile_section_font', NULL, NULL),
	('profile_section_text_color', NULL, NULL),
	('profile_settings_tab_highlight', NULL, NULL),
	('profile_userpanel_font', NULL, NULL),
	('profile_userpanel_linkcolor', NULL, NULL),
	('profile_userpanel_textcolor', NULL, NULL),
	('search_result_highlight_color', NULL, NULL),
	('section_divider_color', NULL, NULL),
	('side_nav_avatar_border', NULL, NULL),
	('side_nav_background', NULL, NULL),
	('side_nav_background_active', NULL, NULL),
	('side_nav_background_hover', NULL, NULL),
	('side_nav_border', NULL, NULL),
	('side_nav_item_border_bottom', NULL, NULL),
	('side_nav_item_border_top', NULL, NULL),
	('side_nav_number_messages_color', NULL, NULL),
	('side_nav_text_color', NULL, NULL),
	('side_nav_text_color_active', NULL, NULL),
	('side_nav_text_color_hover', NULL, NULL),
	('slideshow_border', NULL, NULL),
	('slideshow_border_radius_size', NULL, NULL),
	('slideshow_close_button_border', NULL, NULL),
	('slideshow_close_button_border_radius_size', NULL, NULL),
	('slideshow_image_background', NULL, NULL),
	('slideshow_image_text_color', NULL, NULL),
	('slideshow_thumbnail_background', NULL, NULL),
	('slideshow_thumbnail_carousel_background', NULL, NULL),
	('spacing_margin_l', NULL, NULL),
	('spacing_margin_m', NULL, NULL),
	('spacing_margin_s', NULL, NULL),
	('spacing_margin_xl', NULL, NULL),
	('spacing_margin_xs', NULL, NULL),
	('spacing_margin_xxl', NULL, NULL),
	('spacing_padding_l', NULL, NULL),
	('spacing_padding_m', NULL, NULL),
	('spacing_padding_s', NULL, NULL),
	('spacing_padding_xl', NULL, NULL),
	('spacing_padding_xs', NULL, NULL),
	('spacing_padding_xxl', NULL, NULL),
	('sticky_topic_background_color', NULL, NULL),
	('text_tertiary_color', NULL, NULL),
	('thread_reply_background', NULL, NULL),
	('thread_starter_background', NULL, NULL),
	('thread_view_avatar_border', NULL, NULL),
	('time_stamp_color', NULL, NULL),
	('titleimage', NULL, NULL),
	('titleimage_padding', NULL, NULL),
	('toolbar_background', NULL, NULL),
	('toolbar_border', NULL, NULL),
	('toolbar_button_border', NULL, NULL),
	('toolbar_dropdown_background_gradient_end', NULL, NULL),
	('toolbar_dropdown_background_gradient_start', NULL, NULL),
	('toolbar_dropdown_border', NULL, NULL),
	('toolbar_dropdown_divider_color', NULL, NULL),
	('toolbar_dropdown_item_background_active', NULL, NULL),
	('toolbar_dropdown_text_color', NULL, NULL),
	('toolbar_dropdown_text_color_active', NULL, NULL),
	('toolbar_font', NULL, NULL),
	('toolbar_form_field_background', NULL, NULL),
	('toolbar_form_field_border', NULL, NULL),
	('toolbar_form_field_placeholder_text_color', NULL, NULL),
	('toolbar_text_color', NULL, NULL),
	('tooltip_signature_background', NULL, NULL),
	('tooltip_signature_border', NULL, NULL),
	('topbg_header_mainnav_background', NULL, NULL),
	('topbg_header_mainnav_bottom_border', NULL, NULL),
	('topbg_header_mainnav_subnav_background', NULL, NULL),
	('topbg_header_mainnav_subnav_max_width', NULL, NULL),
	('topic_title_color', NULL, NULL),
	('vbmessenger_chatwindow_content_background', NULL, NULL),
	('vbmessenger_chatwindow_message_mine_background', NULL, NULL),
	('vbmessenger_chatwindow_message_theirs_background', NULL, NULL),
	('vbmessenger_chatwindow_participants_background', NULL, NULL),
	('vbmessenger_chatwindow_widget_background', NULL, NULL),
	('wrapper_background', NULL, NULL),
	('wrapper_margin', NULL, NULL),
	('wrapper_max_width', NULL, NULL),
	('wrapper_min_width', NULL, NULL),
	('wrapper_width', NULL, NULL);
/*!40000 ALTER TABLE `documentation_stylevar` ENABLE KEYS */;

-- Dumping structure for table vb5_manual.documentation_stylevargroup
DROP TABLE IF EXISTS `documentation_stylevargroup`;
CREATE TABLE IF NOT EXISTS `documentation_stylevargroup` (
  `stylevargroup` varchar(250) NOT NULL,
  `documentation` text NOT NULL,
  `imagepath` varchar(250) NOT NULL,
  PRIMARY KEY (`stylevargroup`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

-- Dumping data for table vb5_manual.documentation_stylevargroup: 0 rows
DELETE FROM `documentation_stylevargroup`;
/*!40000 ALTER TABLE `documentation_stylevargroup` DISABLE KEYS */;
/*!40000 ALTER TABLE `documentation_stylevargroup` ENABLE KEYS */;

-- Dumping structure for table vb5_manual.documentation_widget
DROP TABLE IF EXISTS `documentation_widget`;
CREATE TABLE IF NOT EXISTS `documentation_widget` (
  `guid` varchar(250) NOT NULL,
  `template` varchar(250) NOT NULL,
  `documentation` text,
  `examples` text,
  `imagepath` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

-- Dumping data for table vb5_manual.documentation_widget: 75 rows
DELETE FROM `documentation_widget`;
/*!40000 ALTER TABLE `documentation_widget` DISABLE KEYS */;
INSERT INTO `documentation_widget` (`guid`, `template`, `documentation`, `examples`, `imagepath`) VALUES
	('vbulletin-abstractwidget-global', '', NULL, NULL, NULL),
	('vbulletin-abstractwidget-hideable-588fbfbc1bef97.25185249', '', NULL, NULL, NULL),
	('vbulletin-abstractwidget-activitystream-378bfab93ce996.24191794', '', NULL, NULL, NULL),
	('vbulletin-widget_1-4eb423cfd68cd8.93414606', 'widget_statichtml', NULL, NULL, NULL),
	('vbulletin-widget_2-4eb423cfd691d6.44840082', 'widget_video', NULL, NULL, NULL),
	('vbulletin-widget_4-4eb423cfd69899.61732480', 'widget_activitystream', NULL, NULL, NULL),
	('vbulletin-widget_5-4eb423cfd69bf4.53144655', 'widget_channeldisplay', NULL, NULL, NULL),
	('vbulletin-widget_6-4eb423cfd69f41.95279534', 'widget_conversationdisplay', NULL, NULL, NULL),
	('vbulletin-widget_7-4eb423cfd6a2a9.88882814', 'widget_subchannelsdisplay', NULL, NULL, NULL),
	('vbulletin-abstractwidget-search-2fa249eca7b4f8.97225605', '', NULL, NULL, NULL),
	('vbulletin-widget_search-4eb423cfd6a5f3.08329785', 'widget_search', NULL, NULL, NULL),
	('vbulletin-widget_search-friends-4eb423cfd6a5f3.08320765', 'widget_search', NULL, NULL, NULL),
	('vbulletin-widget_search-trending-4eb423cfd6a5f3.08320765', 'widget_search', NULL, NULL, NULL),
	('vbulletin-abstractwidget-search2-4ef1774cf862cd.82303595', 'widget_search2', NULL, NULL, NULL),
	('vbulletin-widget-upcomingevents-33f29410ce3a1f.70591930', 'widget_search2', NULL, NULL, NULL),
	('vbulletin-widget_9-4eb423cfd6a956.90724117', 'widget_onlineusers', NULL, NULL, NULL),
	('vbulletin-widget_search_criteria-4eb423cfd6aca9.42470675', 'widget_search_criteria', NULL, NULL, NULL),
	('vbulletin-widget_11-4eb423cfd6b002.64783616', 'widget_register', NULL, NULL, NULL),
	('vbulletin-widget_12-4eb423cfd6b362.34901422', 'widget_onlineuserdetails', NULL, NULL, NULL),
	('vbulletin-widget_13-4eb423cfd6b6b0.89761798', 'widget_tagcloud', NULL, NULL, NULL),
	('vbulletin-widget_search_results-4eb423cfd6ba10.05943316', 'widget_search_results', NULL, NULL, NULL),
	('vbulletin-widget_15-4eb423cfd6bd63.20171439', 'widget_php', NULL, NULL, NULL),
	('vbulletin-widget_top_active_users-4eb423cfd6c0c8.67950126', 'widget_top_active_users', NULL, NULL, NULL),
	('vbulletin-widget_photos-4eb423cfd6c410.69095735', 'widget_photos', NULL, NULL, NULL),
	('vbulletin-widget_settings-4eb423cfd6d166.73559252', 'widget_settings', NULL, NULL, NULL),
	('vbulletin-widget_profile-4eb423cfd6d4b0.24011159', 'widget_profile', NULL, NULL, NULL),
	('vbulletin-widget_media-4eb423cfd6d802.93687555', 'widget_media', NULL, NULL, NULL),
	('vbulletin-widget_profile_sidebar-4eb423cfd6d811.94687666', 'widget_profile_sidebar', NULL, NULL, NULL),
	('vbulletin-widget_birthday-4eb423cfd6db59.51474795', 'widget_birthday', NULL, NULL, NULL),
	('vbulletin-widget_privatemessages-4eb423cfd6dea7.34930839', 'widget_privatemessage_display', NULL, NULL, NULL),
	('vbulletin-widget_subscription-4eb423cfd6dea7.34930840', 'widget_subscription', NULL, NULL, NULL),
	('vbulletin-widget_privatemessages-4eb423cfd6dea7.34930841', 'widget_privatemessage_navigation', NULL, NULL, NULL),
	('vbulletin-widget_privatemessages-4eb423cfd6dea7.34930842', 'widget_privatemessage_search', NULL, NULL, NULL),
	('vbulletin-widget_privatemessages-4eb423cfd6dea7.34930843', 'widget_privatemessage_toolbar', NULL, NULL, NULL),
	('vbulletin-widget_album-4eb423cfd6dea7.34930844', 'widget_album', NULL, NULL, NULL),
	('vbulletin-widget_announcement-4eb423cfd6dea7.34930845', 'widget_announcement', NULL, NULL, NULL),
	('vbulletin-widget_visitormessage-4eb423cfd6dea7.34930846', 'widget_visitormessage_display', NULL, NULL, NULL),
	('vbulletin-widget_forgot_password-4eb423cfd6dea7.34930847', 'widget_forgot_password', NULL, NULL, NULL),
	('vbulletin-widget_blogadmin-4eb423cfd6dea7.34930848', 'widget_blogadmin', NULL, NULL, NULL),
	('vbulletin-widget_bloghome-4eb423cfd6dea7.34930849', 'widget_bloghome', NULL, NULL, NULL),
	('vbulletin-widget_blogcategories-4eb423cfd6dea7.34930850', 'widget_blogcategories', NULL, NULL, NULL),
	('vbulletin-widget_blogsummary-4eb423cfd6dea7.34930852', 'widget_blogsummary', NULL, NULL, NULL),
	('vbulletin-widget_blogchanneldisplay-4eb423cfd6dea7.34930853', 'widget_blogchanneldisplay', NULL, NULL, NULL),
	('vbulletin-widget_newcontent-4eb423cfd6dea7.34930855', 'widget_newcontent', NULL, NULL, NULL),
	('vbulletin-widget_newcontent-4eb423cfd6dea7.34930856', 'widget_ad', NULL, NULL, NULL),
	('vbulletin-contactus-4eb423cfd6dea7.34930857', 'widget_contactus', NULL, NULL, NULL),
	('vbulletin-help-4eb423cfd6dea7.34930858', 'widget_help', NULL, NULL, NULL),
	('vbulletin-widget_sgadmin-4eb423cfd6dea7.34930858', 'widget_sgadmin', NULL, NULL, NULL),
	('vbulletin-widget_sghome-4eb423cfd6dea7.34930859', 'widget_sghome', NULL, NULL, NULL),
	('vbulletin-widget_sgcategories-4eb423cfd6dea7.34930860', 'widget_sgcategories', NULL, NULL, NULL),
	('vbulletin-widget_groupsummary-4eb423cfd6dea7.34930863', 'widget_groupsummary', NULL, NULL, NULL),
	('vbulletin-widget_sgcategorylist-4eb423cfd6dea7.34930865', 'widget_sgcategorylist', NULL, NULL, NULL),
	('vbulletin-widget_sgchanneldisplay-4eb423cfd6dea7.34930866', 'widget_sgchanneldisplay', NULL, NULL, NULL),
	('vbulletin-widget_container-4eb423cfd6dea7.34930867', 'widget_container', NULL, NULL, NULL),
	('vbulletin-widget_activate_user-4eb423cfd6dea7.34930868', 'widget_activate_user', NULL, NULL, NULL),
	('vbulletin-widget_activate_user-4eb423cfd6dea7.34930869', 'widget_activate_email', NULL, NULL, NULL),
	('vbulletin-widget_page_title-4eb423cfd6dea7.34930870', 'widget_pagetitle', NULL, NULL, NULL),
	('vbulletin-widget_coppa_form-4eb423cfd6dea7.34930871', 'widget_coppa_form', NULL, NULL, NULL),
	('vbulletin-widget_css_examples-513e3a82333a00.09897130', 'widget_css_examples', NULL, NULL, NULL),
	('vbulletin-widget_memberlist-4eb423cfd6dea7.34930873', 'widget_memberlist', NULL, NULL, NULL),
	('vbulletin-widget_cmschanneldisplay-4eb423cfd6dea7.34930874', 'widget_cmschanneldisplay', NULL, NULL, NULL),
	('vbulletin-widget_cmschannelnavigation-4eb423cfd6dea7.34930875', 'widget_cmschannelnavigation', NULL, NULL, NULL),
	('vbulletin-widget_tagnavigation-4eb423cfd6dea7.34930876', 'widget_tagnavigation', NULL, NULL, NULL),
	('vbulletin-widget_articledisplay-4eb423cfd6dea7.34930877', 'widget_articledisplay', NULL, NULL, NULL),
	('vbulletin-widget_aboutauthor-4eb423cfd6dea7.34930878', 'widget_aboutauthor', NULL, NULL, NULL),
	('vbulletin-widget_statistics-4eb423cfd6dea7.34930879', 'widget_statistics', NULL, NULL, NULL),
	('vbulletin-widget_contentslider-4eb423cfd6dea7.34930880', 'widget_contentslider', NULL, NULL, NULL),
	('vbulletin-widget_markup_library-55129b3ac88d9001.1908834732', 'widget_markup_library', NULL, NULL, NULL),
	('vbulletin-widget_apiform-5605ae410cfe70.79574745', 'widget_apiform', NULL, NULL, NULL),
	('vbulletin-widget-resetpassword-5697f9156379b6.02050140', 'widget_resetpassword_form', NULL, NULL, NULL),
	('vbulletin-pmchat-widget-chat-573cb2b3a78a93.12390691', 'pmchat_widget_chat', NULL, NULL, NULL),
	('vbulletin-widget_channel_description-580aaf0629f7e0.23352381', 'widget_channeldescription', NULL, NULL, NULL),
	('vbulletin-widget_calendar-589a1d028d8fc3.56111552', 'widget_calendar', NULL, NULL, NULL),
	('vbulletin-abstractwidget-tabbedcontainer-589ba8fcabe8f9.47298585', 'widget_tabbedcontainer', NULL, NULL, NULL),
	('vbulletin-widget-tabbedcontainer-589ba9e36d36c9.90641387', 'widget_tabbedcontainer', NULL, NULL, NULL);
/*!40000 ALTER TABLE `documentation_widget` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
